use std::collections::HashMap;

use macroquad::prelude::*;

// Placeholder tile art (256x256 PNG), generated by tools\gen_tile_images.ps1.
// Replace any file with high-quality art, keeping the same file name; the game
// falls back to the procedural icon when a file is missing. Files are embedded
// at compile time so they work on Android too.

static TILE_IMAGES: &[(&str, &[u8])] = &[
    ("SOL", include_bytes!("../../assets/tiles/sol.png")),
    ("USDC", include_bytes!("../../assets/tiles/usdc.png")),
    ("USDT", include_bytes!("../../assets/tiles/usdt.png")),
    ("BONK", include_bytes!("../../assets/tiles/bonk.png")),
    ("WIF", include_bytes!("../../assets/tiles/wif.png")),
    ("JUP", include_bytes!("../../assets/tiles/jup.png")),
    ("RAY", include_bytes!("../../assets/tiles/ray.png")),
    ("ORCA", include_bytes!("../../assets/tiles/orca.png")),
    ("PYTH", include_bytes!("../../assets/tiles/pyth.png")),
    ("JTO", include_bytes!("../../assets/tiles/jto.png")),
    ("Swap", include_bytes!("../../assets/tiles/swap.png")),
    ("Stake", include_bytes!("../../assets/tiles/stake.png")),
    ("Lend", include_bytes!("../../assets/tiles/lend.png")),
    ("Yield", include_bytes!("../../assets/tiles/yield.png")),
    ("Bridge", include_bytes!("../../assets/tiles/bridge.png")),
    ("DAO", include_bytes!("../../assets/tiles/dao.png")),
    ("NFT", include_bytes!("../../assets/tiles/nft.png")),
    ("Mint", include_bytes!("../../assets/tiles/mint.png")),
    ("Pool", include_bytes!("../../assets/tiles/pool.png")),
    ("Farm", include_bytes!("../../assets/tiles/farm.png")),
    ("Saga", include_bytes!("../../assets/tiles/saga.png")),
    ("Firedancer", include_bytes!("../../assets/tiles/firedancer.png")),
    ("Token2022", include_bytes!("../../assets/tiles/token2022.png")),
    ("Program", include_bytes!("../../assets/tiles/program.png")),
    ("Account", include_bytes!("../../assets/tiles/account.png")),
    ("Block", include_bytes!("../../assets/tiles/block.png")),
    ("Vote", include_bytes!("../../assets/tiles/vote.png")),
    ("Wallet", include_bytes!("../../assets/tiles/wallet.png")),
    ("Jito", include_bytes!("../../assets/tiles/jito.png")),
    ("Marinade", include_bytes!("../../assets/tiles/marinade.png")),
    ("Lido", include_bytes!("../../assets/tiles/lido.png")),
    ("Rocket", include_bytes!("../../assets/tiles/rocket.png")),
    ("Figment", include_bytes!("../../assets/tiles/figment.png")),
    ("Anza", include_bytes!("../../assets/tiles/anza.png")),
    ("Triton", include_bytes!("../../assets/tiles/triton.png")),
    ("Helius", include_bytes!("../../assets/tiles/helius.png")),
];

pub struct TileTextures {
    textures: HashMap<String, Texture2D>,
}

impl TileTextures {
    pub fn new_empty() -> Self {
        Self {
            textures: HashMap::new(),
        }
    }

    pub async fn load() -> Self {
        let mut textures = HashMap::with_capacity(TILE_IMAGES.len());
        for (name, bytes) in TILE_IMAGES {
            if let Ok(img) = Image::from_file_with_format(bytes, Some(ImageFormat::Png)) {
                let tex = Texture2D::from_image(&img);
                tex.set_filter(FilterMode::Linear);
                textures.insert(name.to_string(), tex);
            }
        }
        Self { textures }
    }

    pub fn get(&self, name: &str) -> Option<&Texture2D> {
        self.textures.get(name)
    }
}